import { Link, Node } from "./types";

type GraphData = {
  nodes: Node[];
  links: Link[];
};

export const data: GraphData = {
  nodes: [
    {
      id: "algorand-python",
      name: "algorand-python",
      owner: "algorand_foundation",
      language: "python",
      type: "dependency",
      version: ["3.4.1", "No Valid Version"],
    },
    {
      id: "algorand-python-python",
      name: "python",
      version: [">=3.10,<3.14", "^3.12", "^3.10"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-typing-extensions",
      name: "typing-extensions",
      version: ["^4.11.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-attrs",
      name: "attrs",
      version: ["^24.2.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-structlog",
      name: "structlog",
      version: ["^24.1.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-docstring-parser",
      name: "docstring-parser",
      version: [">=0.14.1"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-pycryptodomex",
      name: "pycryptodomex",
      version: [">=3.6.0,<4"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-immutabledict",
      name: "immutabledict",
      version: ["^4.2.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-packaging",
      name: "packaging",
      version: ["^24.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-colorama",
      name: "colorama",
      version: ["No Valid Version"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-mypy_extensions",
      name: "mypy_extensions",
      version: ["^1.0.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-cattrs",
      name: "cattrs",
      version: ["^24.1"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algorand-python-black",
      name: "black",
      version: ["^24.8.0", "No Valid Version"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algorand-python-mypy",
      name: "mypy",
      version: ["1.11.0", "^1.0.0", "*", "^1.5.1", "^1.10.1"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algorand-python-ruff",
      name: "ruff",
      version: ["^0.5.0", ">=0.1.6,<0.5.0", "^0.1.6", "^0.5.4"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algorand-python-pre-commit",
      name: "pre-commit",
      version: ["^3.4.0", "^3.3.2", "^3.8.0", "^3.3.3", ">=2.20,<4.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algorand-python-ruff-lsp",
      name: "ruff-lsp",
      version: ["*"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algorand-python-poethepoet",
      name: "poethepoet",
      version: ["^0.24.4", ">=0.17.1,<0.27.0", "^0.20.0", ">=0.19,<0.26"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit",
      name: "algokit",
      owner: "algorand_foundation",
      language: "python",
      type: "dependency",
      version: ["2.4.2"],
    },
    {
      id: "algokit-click",
      name: "click",
      version: ["^8.1.3"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-httpx",
      name: "httpx",
      version: ["^0.23.1"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-copier",
      name: "copier",
      version: ["^9.2.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-questionary",
      name: "questionary",
      version: ["^1.10.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-pyclip",
      name: "pyclip",
      version: ["^0.7.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-shellingham",
      name: "shellingham",
      version: ["^1.5.4"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-tomli",
      name: "tomli",
      version: ["No Valid Version"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-python-dotenv",
      name: "python-dotenv",
      version: ["^1.0.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-mslex",
      name: "mslex",
      version: ["^1.1.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-keyring",
      name: "keyring",
      version: ["25.2.1"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-pyjwt",
      name: "pyjwt",
      version: ["^2.8.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-cryptography",
      name: "cryptography",
      version: ["^43.0.1"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-algokit-utils",
      name: "algokit-utils",
      version: ["2.3.2", "^2.3.0"],
      owner: "algorand_foundation",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-multiformats",
      name: "multiformats",
      version: ["0.3.1", "^13.1.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-multiformats_config",
      name: "multiformats_config",
      version: ["0.3.1"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-jsondiff",
      name: "jsondiff",
      version: ["^2.0.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-requests",
      name: "requests",
      version: ["^2.31.0"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-pyinstaller",
      name: "pyinstaller",
      version: ["No Valid Version"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-pytest",
      name: "pytest",
      version: ["*", "^7.2.0", "^8.2.2"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-pip-audit",
      name: "pip-audit",
      version: ["^2.4.7", "^2.5.6", "^2.5.5"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-approvaltests",
      name: "approvaltests",
      version: ["^7.2.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-pytest-mock",
      name: "pytest-mock",
      version: ["^3.10.0", "^3.11.1"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-pytest-httpx",
      name: "pytest-httpx",
      version: ["^0.21.2", "^0.21.3"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-python-semantic-release",
      name: "python-semantic-release",
      version: ["^7.34.3", "^7.32.2", "^7.33.4", "^9.8.8"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-pytest-cov",
      name: "pytest-cov",
      version: ["^4.0.0", "*", "^4.1.0", "^5.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-sphinx",
      name: "sphinx",
      version: ["^6.0.0", "^7.2.6", "^6.1.3"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-sphinx-click",
      name: "sphinx-click",
      version: ["^4.4.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-sphinxnotes-markdown-builder",
      name: "sphinxnotes-markdown-builder",
      version: ["^0.5.6"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-gfm-toc",
      name: "gfm-toc",
      version: ["^0.0.7"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-pytest-xdist",
      name: "pytest-xdist",
      version: ["^3.5.0", "^3.4.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-py-algorand-sdk",
      name: "py-algorand-sdk",
      version: ["^2.4.0", "^2.6.1"],
      owner: "algorand_technologies",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-utils-deprecated",
      name: "deprecated",
      version: ["^1.2.14"],
      owner: "other",
      type: "dependency",
      language: "python",
    },
    {
      id: "algokit-utils-myst-parser",
      name: "myst-parser",
      version: ["^1.0.0", "^4.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-sphinx-copybutton",
      name: "sphinx-copybutton",
      version: ["^0.5.2", "^0.5.1"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-sphinx-rtd-theme",
      name: "sphinx-rtd-theme",
      version: ["^1.2.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-sphinx-autodoc2",
      name: "sphinx-autodoc2",
      version: ["^0.5.0", ">=0.4.2,<0.6.0"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-beaker-pyteal",
      name: "beaker-pyteal",
      version: ["^1.1.1"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-types-deprecated",
      name: "types-deprecated",
      version: ["^1.2.9.2"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-sphinx-markdown-builder",
      name: "sphinx-markdown-builder",
      version: ["^0.6.6"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-utils-linkify-it-py",
      name: "linkify-it-py",
      version: ["^2.0.3"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-client-generator",
      name: "algokit-client-generator",
      owner: "algorand_foundation",
      language: "python",
      type: "dependency",
      version: ["1.1.7"],
    },
    {
      id: "algokit-subscriber",
      name: "algokit-subscriber",
      owner: "algorand_foundation",
      language: "python",
      type: "dependency",
      version: ["1.0.0-beta.2"],
    },
    {
      id: "algokit-subscriber-furo",
      name: "furo",
      version: ["^2024.1.29"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-subscriber-sphinx-autobuild",
      name: "sphinx-autobuild",
      version: ["^2024.4.16"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-subscriber-sphinx-mermaid",
      name: "sphinx-mermaid",
      version: ["^0.0.8"],
      owner: "other",
      type: "dev-dependency",
      language: "python",
    },
    {
      id: "algokit-lora",
      name: "algokit-lora",
      owner: "algorand_foundation",
      language: "javascript",
      type: "dependency",
      version: ["0.0.0"],
    },
    {
      id: "algokit-lora-@algorandfoundation/algokit-subscriber",
      name: "@algorandfoundation/algokit-subscriber",
      version: ["1.0.0", "^2.0.3"],
      owner: "algorand_foundation",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@algorandfoundation/algokit-utils",
      name: "@algorandfoundation/algokit-utils",
      version: [
        "^6.1.0",
        "0.1.0",
        "^7.0.0-beta.10",
        "^7.0.0-beta.15",
        "^7.0.0-beta.16",
      ],
      owner: "algorand_foundation",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@auth0/auth0-react",
      name: "@auth0/auth0-react",
      version: ["^2.2.4"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@blockshake/defly-connect",
      name: "@blockshake/defly-connect",
      version: ["^1.1.6"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@daffiwallet/connect",
      name: "@daffiwallet/connect",
      version: ["^1.0.3"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@dnd-kit/core",
      name: "@dnd-kit/core",
      version: ["^6.1.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@dnd-kit/modifiers",
      name: "@dnd-kit/modifiers",
      version: ["^7.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@dnd-kit/sortable",
      name: "@dnd-kit/sortable",
      version: ["^8.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@dnd-kit/utilities",
      name: "@dnd-kit/utilities",
      version: ["^3.2.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@hookform/resolvers",
      name: "@hookform/resolvers",
      version: ["^3.9.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@perawallet/connect",
      name: "@perawallet/connect",
      version: ["^1.3.4"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-accordion",
      name: "@radix-ui/react-accordion",
      version: ["^1.2.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-checkbox",
      name: "@radix-ui/react-checkbox",
      version: ["^1.1.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-dialog",
      name: "@radix-ui/react-dialog",
      version: ["^1.0.5"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-dropdown-menu",
      name: "@radix-ui/react-dropdown-menu",
      version: ["^2.0.6"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-icons",
      name: "@radix-ui/react-icons",
      version: ["^1.3.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-label",
      name: "@radix-ui/react-label",
      version: ["^2.0.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-navigation-menu",
      name: "@radix-ui/react-navigation-menu",
      version: ["^1.1.4"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-popover",
      name: "@radix-ui/react-popover",
      version: ["^1.0.7"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-radio-group",
      name: "@radix-ui/react-radio-group",
      version: ["^1.2.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-select",
      name: "@radix-ui/react-select",
      version: ["^2.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-separator",
      name: "@radix-ui/react-separator",
      version: ["^1.1.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-slot",
      name: "@radix-ui/react-slot",
      version: ["^1.0.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-switch",
      name: "@radix-ui/react-switch",
      version: ["^1.1.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-tabs",
      name: "@radix-ui/react-tabs",
      version: ["^1.0.4"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@radix-ui/react-tooltip",
      name: "@radix-ui/react-tooltip",
      version: ["^1.0.7"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@tanstack/react-table",
      name: "@tanstack/react-table",
      version: ["^8.16.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@tauri-apps/api",
      name: "@tauri-apps/api",
      version: ["^1.5.3"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@txnlab/use-wallet",
      name: "@txnlab/use-wallet",
      version: ["2.8.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@xstate/react",
      name: "@xstate/react",
      version: ["^4.1.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-class-variance-authority",
      name: "class-variance-authority",
      version: ["^0.7.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-clsx",
      name: "clsx",
      version: ["^2.1.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-cmdk",
      name: "cmdk",
      version: ["^1.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-date-fns",
      name: "date-fns",
      version: ["^3.5.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-decimal.js",
      name: "decimal.js",
      version: ["^10.4.3"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-html2canvas-pro",
      name: "html2canvas-pro",
      version: ["^1.5.8"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-idb",
      name: "idb",
      version: ["^8.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-isutf8",
      name: "isutf8",
      version: ["^4.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-jotai",
      name: "jotai",
      version: ["^2.7.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-jotai-effect",
      name: "jotai-effect",
      version: ["^0.6.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-jotai-xstate",
      name: "jotai-xstate",
      version: ["^0.5.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-jsonschema",
      name: "jsonschema",
      version: ["^1.4.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-lucide-react",
      name: "lucide-react",
      version: ["^0.356.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-lute-connect",
      name: "lute-connect",
      version: ["^1.2.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-msw",
      name: "msw",
      version: ["^2.4.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react",
      name: "react",
      version: ["^18.2.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-dom",
      name: "react-dom",
      version: ["^18.2.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-hook-form",
      name: "react-hook-form",
      version: ["^7.52.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-idle-timer",
      name: "react-idle-timer",
      version: ["^5.7.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-json-view-lite",
      name: "react-json-view-lite",
      version: ["^1.4.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-number-format",
      name: "react-number-format",
      version: ["^5.4.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-router-dom",
      name: "react-router-dom",
      version: ["6.24.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-react-toastify",
      name: "react-toastify",
      version: ["^10.0.5"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-tailwind-merge",
      name: "tailwind-merge",
      version: ["^2.2.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-tailwindcss-animate",
      name: "tailwindcss-animate",
      version: ["^1.0.7"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-use-debounce",
      name: "use-debounce",
      version: ["^10.0.3"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-uuid",
      name: "uuid",
      version: ["^9.0.0", "^10.0.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-vaul",
      name: "vaul",
      version: ["^0.9.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-xstate",
      name: "xstate",
      version: ["^5.17.4"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-zod",
      name: "zod",
      version: ["^3.23.8"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-zod-form-data",
      name: "zod-form-data",
      version: ["^2.0.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@makerx/eslint-config",
      name: "@makerx/eslint-config",
      version: ["^3.1.0", "3.1.1", "^3.1.1"],
      owner: "makerx",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@makerx/prettier-config",
      name: "@makerx/prettier-config",
      version: ["^2.0.1", "2.0.1", "^2.0.0"],
      owner: "makerx",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@makerx/ts-config",
      name: "@makerx/ts-config",
      version: ["1.0.1", "^1.0.1"],
      owner: "makerx",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@makerx/ts-dossier",
      name: "@makerx/ts-dossier",
      version: ["^3.0.0"],
      owner: "makerx",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@tauri-apps/cli",
      name: "@tauri-apps/cli",
      version: ["^1.5.11"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@testing-library/jest-dom",
      name: "@testing-library/jest-dom",
      version: ["^6.5.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@testing-library/react",
      name: "@testing-library/react",
      version: ["^14.2.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@testing-library/user-event",
      name: "@testing-library/user-event",
      version: ["^14.5.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@types/node",
      name: "@types/node",
      version: ["^20.11.26", "^18.18.11"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@types/react",
      name: "@types/react",
      version: ["^18.2.56"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@types/react-dom",
      name: "@types/react-dom",
      version: ["^18.2.19"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@types/uuid",
      name: "@types/uuid",
      version: ["^10.0.0", "^9.0.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@typescript-eslint/eslint-plugin",
      name: "@typescript-eslint/eslint-plugin",
      version: ["^7.0.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@typescript-eslint/parser",
      name: "@typescript-eslint/parser",
      version: ["^7.0.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-@vitejs/plugin-react-swc",
      name: "@vitejs/plugin-react-swc",
      version: ["^3.7.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-autoprefixer",
      name: "autoprefixer",
      version: ["^10.4.18"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-better-npm-audit",
      name: "better-npm-audit",
      version: ["^3.7.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-conventional-changelog-conventionalcommits",
      name: "conventional-changelog-conventionalcommits",
      version: ["6.1.0", "^7.0.2", "7.0.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-cpy-cli",
      name: "cpy-cli",
      version: ["^5.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-eslint",
      name: "eslint",
      version: ["8.22.0", "^8.56.0", "^8.47.0", "8.57.0", "8.56.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-eslint-config-prettier",
      name: "eslint-config-prettier",
      version: ["^9.1.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-eslint-plugin-prettier",
      name: "eslint-plugin-prettier",
      version: ["^5.1.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-eslint-plugin-react-hooks",
      name: "eslint-plugin-react-hooks",
      version: ["^4.6.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-eslint-plugin-react-refresh",
      name: "eslint-plugin-react-refresh",
      version: ["^0.4.5"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-eslint-plugin-tailwindcss",
      name: "eslint-plugin-tailwindcss",
      version: ["^3.15.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-fake-indexeddb",
      name: "fake-indexeddb",
      version: ["^6.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-happy-dom",
      name: "happy-dom",
      version: ["^15.7.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-npm-run-all",
      name: "npm-run-all",
      version: ["^4.1.5"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-patch-package",
      name: "patch-package",
      version: ["^8.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-postcss",
      name: "postcss",
      version: ["^8.4.35"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-prettier",
      name: "prettier",
      version: ["3.3.3", "^3.2.4", "^3.0.2", "^3.2.5", "3.2.5"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-prettier-plugin-tailwindcss",
      name: "prettier-plugin-tailwindcss",
      version: ["^0.5.12"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-semantic-release-export-data",
      name: "semantic-release-export-data",
      version: ["^1.0.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-tailwindcss",
      name: "tailwindcss",
      version: ["^3.4.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-typescript",
      name: "typescript",
      version: [
        "^5.6.3",
        "^5.3.3",
        "^5.5.4",
        "^5.4.3",
        ">=5.1.6 <5.5",
        "^5.6.2",
      ],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-vite",
      name: "vite",
      version: ["^5.4.9"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-vite-plugin-node-polyfills",
      name: "vite-plugin-node-polyfills",
      version: ["^0.22.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-lora-vitest",
      name: "vitest",
      version: ["^2.1.1", "^2.1.3", "^1.4.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-buffer",
      name: "buffer",
      version: ["^6.0.3"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@algorandfoundation/tealscript",
      name: "@algorandfoundation/tealscript",
      version: ["^0.105.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@commitlint/cli",
      name: "@commitlint/cli",
      version: ["^18.4.2", "^18.6.0", "^18.4.3", "^19.2.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@commitlint/config-conventional",
      name: "@commitlint/config-conventional",
      version: ["^18.6.0", "^17.7.0", "^18.4.3", "^19.1.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@rollup/plugin-node-resolve",
      name: "@rollup/plugin-node-resolve",
      version: ["^15.2.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@rollup/plugin-typescript",
      name: "@rollup/plugin-typescript",
      version: ["^11.1.6"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@tsconfig/node18",
      name: "@tsconfig/node18",
      version: ["^18.2.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@tsconfig/node20",
      name: "@tsconfig/node20",
      version: ["^20.1.2", "^20.1.4"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-@types/jest",
      name: "@types/jest",
      version: ["^29.5.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-algosdk",
      name: "algosdk",
      version: ["^2.7.0", "^2.9.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-dotenv-cli",
      name: "dotenv-cli",
      version: ["^7.3.0", "^7.4.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-fast-glob",
      name: "fast-glob",
      version: ["^3.3.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-jest-fetch-mock",
      name: "jest-fetch-mock",
      version: ["^3.0.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-magic-string",
      name: "magic-string",
      version: ["^0.30.7"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-replace-in-files-cli",
      name: "replace-in-files-cli",
      version: ["^2.2.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-rimraf",
      name: "rimraf",
      version: ["^5.0.1", "^5.0.5"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-rollup",
      name: "rollup",
      version: ["^4.9.6", "^4.22.5", "^4.13.0", "^4.21.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-semantic-release",
      name: "semantic-release",
      version: ["^23.0.0", "^22.0.10", "^23.0.8", "^23.0.6"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-tiny-invariant",
      name: "tiny-invariant",
      version: ["^1.3.1", "^1.3.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-ts-jest",
      name: "ts-jest",
      version: ["^29.2.5", "^29.1.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-ts-node",
      name: "ts-node",
      version: ["^10.9.2", "^10.9.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-typedoc",
      name: "typedoc",
      version: ["^0.25.4", "^0.26.7"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-typedoc-plugin-markdown",
      name: "typedoc-plugin-markdown",
      version: ["^4.2.8", "^3.17.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-algorand-msgpack",
      name: "algorand-msgpack",
      version: ["^1.0.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-hi-base32",
      name: "hi-base32",
      version: ["^0.5.1"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-js-sha512",
      name: "js-sha512",
      version: ["^0.9.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-@prisma/client",
      name: "@prisma/client",
      version: ["^5.15.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-@vitest/coverage-v8",
      name: "@vitest/coverage-v8",
      version: ["^1.4.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-cross-env",
      name: "cross-env",
      version: ["^7.0.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-prisma",
      name: "prisma",
      version: ["^5.15.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-subscriber-ts-node-dev",
      name: "ts-node-dev",
      version: ["^2.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator",
      name: "@algorandfoundation/algokit-client-generator",
      owner: "algorand_foundation",
      language: "javascript",
      type: "dependency",
      version: ["0.0.0"],
    },
    {
      id: "@algorandfoundation/algokit-client-generator-chalk",
      name: "chalk",
      version: ["^4.1.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-change-case",
      name: "change-case",
      version: ["^4.1.2"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-commander",
      name: "commander",
      version: ["^11.1.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-@noble/ed25519",
      name: "@noble/ed25519",
      version: ["2.0.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-@rollup/plugin-json",
      name: "@rollup/plugin-json",
      version: ["^6.1.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-@types/wait-on",
      name: "@types/wait-on",
      version: ["^5.3.4"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-copyfiles",
      name: "copyfiles",
      version: ["^2.4.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-json-schema-to-typescript",
      name: "json-schema-to-typescript",
      version: ["^13.1.2"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-tsd",
      name: "tsd",
      version: ["^0.30.4"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-tsx",
      name: "tsx",
      version: ["^4.7.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-client-generator-wait-on",
      name: "wait-on",
      version: ["^8.0.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger",
      name: "algokit-avm-vscode-debugger",
      owner: "algorand_foundation",
      language: "javascript",
      type: "dependency",
      version: ["0.1.0"],
    },
    {
      id: "algokit-avm-vscode-debugger-avm-debug-adapter",
      name: "avm-debug-adapter",
      version: ["^0.2.0"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-lodash",
      name: "lodash",
      version: ["^4.17.21"],
      owner: "other",
      type: "dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@types/json-bigint",
      name: "@types/json-bigint",
      version: ["^1.0.4"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@types/lodash",
      name: "@types/lodash",
      version: ["^4.17.7"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@types/mocha",
      name: "@types/mocha",
      version: ["^10.0.7"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@types/vscode",
      name: "@types/vscode",
      version: ["^1.92.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@vscode/vsce",
      name: "@vscode/vsce",
      version: ["^2.22.0"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@wdio/cli",
      name: "@wdio/cli",
      version: ["^8.33.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@wdio/local-runner",
      name: "@wdio/local-runner",
      version: ["^8.33.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@wdio/mocha-framework",
      name: "@wdio/mocha-framework",
      version: ["^8.33.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-@wdio/spec-reporter",
      name: "@wdio/spec-reporter",
      version: ["^8.32.4"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-esbuild",
      name: "esbuild",
      version: ["^0.23.1"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-mocha",
      name: "mocha",
      version: ["^10.7.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-semantic-release-vsce",
      name: "semantic-release-vsce",
      version: ["^5.7.4"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "algokit-avm-vscode-debugger-wdio-vscode-service",
      name: "wdio-vscode-service",
      version: ["^6.0.3"],
      owner: "other",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      id: "@algorandfoundation/algokit-utils-debug",
      name: "@algorandfoundation/algokit-utils-debug",
      owner: "algorand_foundation",
      language: "javascript",
      type: "dependency",
      version: ["0.1.0"],
    },
  ],
  links: [
    {
      source: "python",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "typing-extensions",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "attrs",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "structlog",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "docstring-parser",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "pycryptodomex",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "immutabledict",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "packaging",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "colorama",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "mypy_extensions",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "cattrs",
      target: "algorand-python",
      type: "dependency",
      language: "python",
    },
    {
      source: "algorand-python",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "black",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "mypy",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "ruff",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pre-commit",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "ruff-lsp",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "poethepoet",
      target: "algorand-python",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "click",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "httpx",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "copier",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "questionary",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "pyclip",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "shellingham",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "tomli",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "python-dotenv",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "mslex",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "keyring",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "pyjwt",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "cryptography",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "algokit-utils",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "multiformats",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "multiformats_config",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "jsondiff",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "requests",
      target: "algokit",
      type: "dependency",
      language: "python",
    },
    {
      source: "pyinstaller",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "ruff",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pip-audit",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "approvaltests",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-mock",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "mypy",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-httpx",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python-semantic-release",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-cov",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pre-commit",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-click",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinxnotes-markdown-builder",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "poethepoet",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "gfm-toc",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-xdist",
      target: "algokit",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python",
      target: "algokit-utils",
      type: "dependency",
      language: "python",
    },
    {
      source: "py-algorand-sdk",
      target: "algokit-utils",
      type: "dependency",
      language: "python",
    },
    {
      source: "httpx",
      target: "algokit-utils",
      type: "dependency",
      language: "python",
    },
    {
      source: "deprecated",
      target: "algokit-utils",
      type: "dependency",
      language: "python",
    },
    {
      source: "pytest",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "ruff",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pip-audit",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-mock",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "mypy",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python-semantic-release",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-cov",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pre-commit",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python-dotenv",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "myst-parser",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-copybutton",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-rtd-theme",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-autodoc2",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "poethepoet",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "beaker-pyteal",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "types-deprecated",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-httpx",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-xdist",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-markdown-builder",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "linkify-it-py",
      target: "algokit-utils",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python",
      target: "algokit-client-generator",
      type: "dependency",
      language: "python",
    },
    {
      source: "algokit-utils",
      target: "algokit-client-generator",
      type: "dependency",
      language: "python",
    },
    {
      source: "ruff",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "mypy",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-cov",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pip-audit",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python-semantic-release",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pre-commit",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "beaker-pyteal",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "poethepoet",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-xdist",
      target: "algokit-client-generator",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "python",
      target: "algokit-subscriber",
      type: "dependency",
      language: "python",
    },
    {
      source: "py-algorand-sdk",
      target: "algokit-subscriber",
      type: "dependency",
      language: "python",
    },
    {
      source: "algokit-utils",
      target: "algokit-subscriber",
      type: "dependency",
      language: "python",
    },
    {
      source: "python-semantic-release",
      target: "algokit-subscriber",
      type: "dependency",
      language: "python",
    },
    {
      source: "mypy",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "ruff",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pre-commit",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "black",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "pytest-cov",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "furo",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "myst-parser",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-autodoc2",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-copybutton",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-autobuild",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "sphinx-mermaid",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "poethepoet",
      target: "algokit-subscriber",
      type: "dev-dependency",
      language: "python",
    },
    {
      source: "@algorandfoundation/algokit-subscriber",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@algorandfoundation/algokit-utils",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@auth0/auth0-react",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@blockshake/defly-connect",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@daffiwallet/connect",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@dnd-kit/core",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@dnd-kit/modifiers",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@dnd-kit/sortable",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@dnd-kit/utilities",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@hookform/resolvers",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@perawallet/connect",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-accordion",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-checkbox",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-dialog",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-dropdown-menu",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-icons",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-label",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-navigation-menu",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-popover",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-radio-group",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-select",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-separator",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-slot",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-switch",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-tabs",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@radix-ui/react-tooltip",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@tanstack/react-table",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@tauri-apps/api",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@txnlab/use-wallet",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@xstate/react",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "class-variance-authority",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "clsx",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "cmdk",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "date-fns",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "decimal.js",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "html2canvas-pro",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "idb",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "isutf8",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "jotai",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "jotai-effect",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "jotai-xstate",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "jsonschema",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "lucide-react",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "lute-connect",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "msw",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "multiformats",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-dom",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-hook-form",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-idle-timer",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-json-view-lite",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-number-format",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-router-dom",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "react-toastify",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "tailwind-merge",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "tailwindcss-animate",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "use-debounce",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "uuid",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "vaul",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "xstate",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "zod",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "zod-form-data",
      target: "algokit-lora",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@makerx/eslint-config",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/prettier-config",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/ts-config",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/ts-dossier",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@tauri-apps/cli",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@testing-library/jest-dom",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@testing-library/react",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@testing-library/user-event",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/node",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/react",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/react-dom",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/uuid",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@typescript-eslint/eslint-plugin",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@typescript-eslint/parser",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@vitejs/plugin-react-swc",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "autoprefixer",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "better-npm-audit",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "conventional-changelog-conventionalcommits",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "cpy-cli",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint-config-prettier",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint-plugin-prettier",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint-plugin-react-hooks",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint-plugin-react-refresh",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint-plugin-tailwindcss",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "fake-indexeddb",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "happy-dom",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "npm-run-all",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "patch-package",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "postcss",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier-plugin-tailwindcss",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release-export-data",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tailwindcss",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typescript",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "vite",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "vite-plugin-node-polyfills",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "vitest",
      target: "algokit-lora",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "buffer",
      target: "@algorandfoundation/algokit-utils",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@algorandfoundation/tealscript",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/cli",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/config-conventional",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/eslint-config",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/prettier-config",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-node-resolve",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-typescript",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@tsconfig/node18",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@tsconfig/node20",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/jest",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/uuid",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "better-npm-audit",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "conventional-changelog-conventionalcommits",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "cpy-cli",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "dotenv-cli",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "fast-glob",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "jest-fetch-mock",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "magic-string",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "npm-run-all",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "replace-in-files-cli",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rimraf",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rollup",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tiny-invariant",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "ts-jest",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "ts-node",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typedoc",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typedoc-plugin-markdown",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typescript",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "uuid",
      target: "@algorandfoundation/algokit-utils",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "@algorandfoundation/algokit-utils",
      type: "peer-dependency",
      language: "javascript",
    },
    {
      source: "algorand-msgpack",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "buffer",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "hi-base32",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "js-sha512",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@prisma/client",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/cli",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/config-conventional",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/eslint-config",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/prettier-config",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-typescript",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@vitest/coverage-v8",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "better-npm-audit",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "conventional-changelog-conventionalcommits",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "cpy-cli",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "cross-env",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "dotenv-cli",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "npm-run-all",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prisma",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rimraf",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rollup",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tiny-invariant",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "ts-node-dev",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typedoc",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typedoc-plugin-markdown",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typescript",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "vitest",
      target: "@algorandfoundation/algokit-subscriber",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@algorandfoundation/algokit-utils",
      target: "@algorandfoundation/algokit-subscriber",
      type: "peer-dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "@algorandfoundation/algokit-subscriber",
      type: "peer-dependency",
      language: "javascript",
    },
    {
      source: "@algorandfoundation/algokit-utils",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "chalk",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "change-case",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "commander",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "jsonschema",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/cli",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/config-conventional",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/eslint-config",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/prettier-config",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/ts-config",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@noble/ed25519",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-json",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-node-resolve",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-typescript",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@tsconfig/node20",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/wait-on",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "better-npm-audit",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "conventional-changelog-conventionalcommits",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "copyfiles",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint-plugin-prettier",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "json-schema-to-typescript",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "npm-run-all",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rimraf",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rollup",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tiny-invariant",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tsd",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tsx",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typescript",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "vitest",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "wait-on",
      target: "@algorandfoundation/algokit-client-generator",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "algokit-avm-vscode-debugger",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "avm-debug-adapter",
      target: "algokit-avm-vscode-debugger",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "lodash",
      target: "algokit-avm-vscode-debugger",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/cli",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/config-conventional",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/eslint-config",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/prettier-config",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/ts-config",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/json-bigint",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/lodash",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/mocha",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/node",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/vscode",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@vscode/vsce",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@wdio/cli",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@wdio/local-runner",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@wdio/mocha-framework",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@wdio/spec-reporter",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "conventional-changelog-conventionalcommits",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "esbuild",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "mocha",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "npm-run-all",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rimraf",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release-vsce",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "ts-node",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typescript",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "wdio-vscode-service",
      target: "algokit-avm-vscode-debugger",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "buffer",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dependency",
      language: "javascript",
    },
    {
      source: "@algorandfoundation/algokit-utils",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/cli",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@commitlint/config-conventional",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/eslint-config",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@makerx/prettier-config",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-json",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-node-resolve",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@rollup/plugin-typescript",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@tsconfig/node18",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@tsconfig/node20",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/jest",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@types/uuid",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "better-npm-audit",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "conventional-changelog-conventionalcommits",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "cpy-cli",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "dotenv-cli",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "eslint",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "fast-glob",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "jest-fetch-mock",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "magic-string",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "npm-run-all",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "prettier",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "replace-in-files-cli",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rimraf",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "rollup",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "semantic-release",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "tiny-invariant",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "ts-jest",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "ts-node",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typedoc",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typedoc-plugin-markdown",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "typescript",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "uuid",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "dev-dependency",
      language: "javascript",
    },
    {
      source: "@algorandfoundation/algokit-utils",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "peer-dependency",
      language: "javascript",
    },
    {
      source: "algosdk",
      target: "@algorandfoundation/algokit-utils-debug",
      type: "peer-dependency",
      language: "javascript",
    },
  ],
};
